import type { Section } from "./data-home";

export const blogData: Section[] = [
  {
    id: "blog_page",
    title: "Blog page",
    subtitle: "Content hub — search, categories, recent posts, email signup",
    tag: "required",
    goal: "Establish authority, educate the ideal customer, and keep visitors on the site longer",
    tip: "Add a search bar to make the page user-friendly. Categories help visitors find relevant content fast.",
    blogTypes: [
      { name: "How-to / educational", desc: "Step-by-step tutorials or explainers that position you as the expert." },
      { name: "Listicle", desc: "Curated lists that are easy to skim and share." },
      { name: "Interview / case study", desc: "Real stories from clients or collaborators that double as social proof." },
      { name: "Review", desc: "Product, tool, or resource reviews that serve your audience's research needs." },
      { name: "Personal / lifestyle", desc: "Behind-the-scenes or personal stories that build connection and brand personality." },
    ],
    prompts: [
      { label: "Blog page headline", text: (c, b, a) => `Write 6 blog page headline options for ${c}'s content hub. Audience: ${a}. Should feel like an invitation to learn, not just a navigation label. Brand type: ${b}.` },
      { label: "Email signup copy", text: (c, b, a) => `Write email list signup copy for the sidebar/header of ${c}'s blog page. Audience: ${a}. Headline + 1-sentence reason to subscribe + button label. Low-commitment and value-forward.` },
      { label: "Content category names", text: (c, b, a) => `Write 8 content category name options for ${c}'s blog. Audience: ${a}. On-brand and specific — not generic labels like "tips" or "news". Each should hint at what the reader will learn.` },
      { label: "Featured post intro", text: (c, b, a) => `Write a short "featured post" framing line for ${c}'s blog page — 1–2 sentences that introduce the featured or most popular article. Audience: ${a}. Warm and click-worthy.` },
    ],
  },
  {
    id: "blog_post",
    title: "Blog post structure",
    subtitle: "H1 headline · H3 subheadline · open loop · H2 section breaks · CTA",
    tag: "required",
    goal: "Deliver value (entertainment, education, or inspiration), establish authority, and end with a clear next step",
    tip: "The best-kept SEO secret: sharing genuinely useful content that people consume and engage with is 80% of the battle. Focus on the human first, algorithm second.",
    formatting: [
      { tag: "H1", role: "Main headline", desc: "Piques curiosity and gets the click. Include a target keyword if it fits naturally — never force it." },
      { tag: "H3", role: "Subheadline", desc: "Appears below the H1. Summarizes the article and includes keywords the audience would search. Keep it concise." },
      { tag: "H2", role: "Section breaks", desc: "Mini-headlines throughout the post. Break up text, transition between points, include keywords. SEO hack: H2 carries more weight than H3, so use it for section breaks." },
      { tag: "Body", role: "Content", desc: "Deliver the promised value. Hook with a strong open loop in the first paragraph. Skimmable with bold/italic emphasis, short paragraphs, and visuals." },
      { tag: "CTA", role: "Closing call-to-action", desc: "Always end with a clear next step: buy, sign up, comment, follow, download." },
    ],
    prompts: [
      { label: "H1 headline options", text: (c, b, a) => `Write 10 H1 blog post headline options for ${c}. Audience: ${a}. Each should pique curiosity, get the click, and naturally include a target keyword. Mix: how-to, listicle, curiosity-gap, and bold-claim angles. Topic: [ADD TOPIC]` },
      { label: "H3 subheadline options", text: (c, b, a) => `Write 6 H3 subheadline options for a blog post on [TOPIC] for ${c}. Audience: ${a}. Each should summarize the article, expand on the H1, and include keywords the audience would search. Concise — under 15 words.` },
      { label: "Open loop intro paragraph", text: (c, b, a) => `Write 3 open loop intro paragraphs for a blog post on [TOPIC] for ${c}. Audience: ${a}. Each should: hook the reader with a surprising stat, relatable scenario, or bold statement — then tease the value to come without revealing it. 50–80 words each.` },
      { label: "H2 section break headlines", text: (c, b, a) => `Write 6 H2 section break headline options for a blog post on [TOPIC] for ${c}. Audience: ${a}. Each should: work as a standalone mini-headline, transition the reader to a new point, and include a relevant keyword naturally.` },
      { label: "Blog post CTA options", text: (c, b, a) => `Write 6 closing CTA options for a ${c} blog post targeting ${a}. Include: the CTA type (lead magnet, email signup, related post, offer), a 1-sentence pitch, and a button label. [ADD TOPIC + RELEVANT OFFER OR RESOURCE]` },
      { label: "Lead magnet mention", text: (c, b, a) => `Write a natural in-post lead magnet mention for ${c}'s blog. Audience: ${a}. 2–3 sentences that feel like a genuine recommendation mid-article — not an ad. Link to a relevant free resource that adds to the value of the post. [ADD LEAD MAGNET DETAILS]` },
    ],
  },
  {
    id: "blog_seo",
    title: "SEO & keywords",
    subtitle: "Short-tail vs long-tail · keyword placement · skimmability",
    tag: "optional",
    goal: 'Give the post that extra 20% of "Google juice" without sacrificing readability for humans',
    tip: "Conversion copywriting (humans first) is 80% of the battle. SEO best practices add the extra 20%.",
    seoNotes: [
      { point: "Short-tail keywords", desc: "3 words or fewer. High volume, high competition. Use them — but long-tail does the heavier lifting." },
      { point: "Long-tail keywords", desc: "More specific phrases. Easier to rank for, more targeted. Most keyword efforts should focus here." },
      { point: "Keyword placement", desc: "H1, H3, H2 headings, first paragraph, naturally throughout body. Never stuff — write for humans." },
      { point: "Skimmability", desc: "Bold, italic, underline for emphasis. Short paragraphs. Images, charts, videos. H2 breaks every few sections." },
      { point: "Internal links", desc: "Link to related posts and offers on your own site. Keeps visitors on the site longer and signals authority to Google." },
      { point: "Ideal length", desc: "1,000–2,000 words is the general benchmark — but write as long as the topic needs. Quality beats length every time." },
    ],
    prompts: [
      { label: "Keyword research brief", text: (c, b, a) => `I'm writing a blog post for ${c} (${b}, audience: ${a}) on [TOPIC]. Give me: (1) 5 short-tail keyword ideas, (2) 10 long-tail keyword phrases my audience would realistically search, (3) 3 related topics I could internally link to.` },
      { label: "SEO title tag + meta description", text: (c, b, a) => `Write 3 SEO title tag and meta description pairs for a ${c} blog post on [TOPIC]. Audience: ${a}. Title tag: under 60 characters, includes primary keyword. Meta description: under 155 characters, curiosity-driven with a clear benefit.` },
      { label: "Internal link anchor text", text: (c, b, a) => `I'm writing a blog post for ${c} on [TOPIC]. Suggest 5 internal linking opportunities — what existing content on the site should I link to, and what anchor text should I use? Audience: ${a}. Brand type: ${b}.` },
    ],
  },
  {
    id: "blog_cta",
    title: "Blog CTA strategy",
    subtitle: "Lead magnet · email signup · related post · offer mention",
    tag: "required",
    goal: "Every post should have a clear next step — capture leads, build the list, or move prospects toward an offer",
    tip: "The sidebar email signup, mid-post lead magnet mentions, and end-of-post CTA all work together. Don't leave readers with nowhere to go.",
    ctaTypes: [
      { name: "Email list signup", desc: "Sidebar or inline — a free resource in exchange for the email. The most important CTA on any blog." },
      { name: "Lead magnet mention", desc: "Mid-post recommendation of a free resource directly relevant to the topic. Feels helpful, not pushy." },
      { name: "Related post", desc: "End-of-post or mid-post links to other content. Keeps visitors on the site and builds trust." },
      { name: "Offer mention", desc: "A natural, non-pushy mention of a paid product or service when it's genuinely the best next step." },
    ],
    prompts: [
      { label: "Sidebar email CTA", text: (c, b, a) => `Write sidebar email signup copy for ${c}'s blog. Audience: ${a}. Headline (6 words max) + 1-sentence value prop + button label. Make the free resource or newsletter feel irresistible. [ADD WHAT THEY'RE OFFERING]` },
      { label: "Mid-post lead magnet copy", text: (c, b, a) => `Write a mid-post lead magnet mention for ${c}'s blog post on [TOPIC]. Audience: ${a}. 2–3 sentences that feel like a genuine recommendation, not an interruption. Includes a link to [FREE RESOURCE NAME].` },
      { label: "End-of-post CTA", text: (c, b, a) => `Write 3 end-of-post CTA options for a ${c} blog post on [TOPIC]. Audience: ${a}. Each: a 1-sentence wrap-up + a clear next step (lead magnet, related post, or offer mention). Warm and helpful — not a hard sell.` },
      { label: "Author bio copy", text: (c, b, a) => `Write a short author bio for ${c}'s blog posts. Audience: ${a}. 2–3 sentences: who they are, what they do, why readers should follow them. Conversational, credible, and personality-forward. Include a CTA to follow on social or join the email list.` },
    ],
  },
];
